### ISSUE TITLE
这个效果用gridlayout能实现么？

### ISSUE THREAD

**Issue by MIkeeJY** [dolphinwang/GridLayout#1]
![qq 20150727191525](https://cloud.githubusercontent.com/assets/8580762/8904802/17140fa6-3495-11e5-994d-af5458ce0b4f.png)

**Comment by MIkeeJY** [comment]
每次都new 一个imageview 根据服务器返回的宽高计算他应该占的大小？

**Comment by dolphinwang** [comment]
可以的，你也可以动态调整之前grdlayout中child的layoutparams，如果不够，再加一些，多出来的就remove掉
